In [3]:
import numpy as np
import torch

# NumPy Review
## 1d Array with NumPy

In [5]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [7]:
print('Rank  of t: ', t.ndim) # rank
print('Sahpe of t: ', t.shape)

Rank  of t:  1
Sahpe of t:  (7,)


In [13]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ',t[2:5], t[4:-1]) # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:]) # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


## 2D Array with Numpy

In [14]:
t = np.array([[1., 2., 3.],[4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [15]:
print('Rank  of t: ', t.ndim) # rank
print('Shape of t:', t.shape)

Rank  of t:  2
Shape of t: (4, 3)


# PyTorch Tensor
## 1D Array with PyTorch

In [16]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [19]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape
print(t[0], t[1], t[-2]) # Element
print(t[2:5], t[4:-1]) # Slicing
print(t[:2], t[3:]) # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(5.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array with PyTorch

In [20]:
t = torch.FloatTensor([[1., 2., 3.],[4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [34]:
print(t.dim()) # rank
print(t.size()) # shape
print(t.shape) # shape
print(t[:, 1]) 
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# Broadcasting

In [24]:
# Same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1)
print(m2)
print(m1 + m2)

tensor([[3., 3.]])
tensor([[2., 2.]])
tensor([[5., 5.]])


In [25]:
# Vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3]]) # m2 : (1,) -> (1,2)
print(m1)
print(m2)
print(m1 + m2)

tensor([[1., 2.]])
tensor([[3.]])
tensor([[4., 5.]])


In [30]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]]) # m1 : (1,2) -> (2,2)
m2 = torch.FloatTensor([[[3],[4]]]) # m2 : (1,2,1) -> (2,2)
print(m1, m1.size())
print(m2,m2.size())
print()
print(m1 + m2)

tensor([[1., 2.]]) torch.Size([1, 2])
tensor([[[3.],
         [4.]]]) torch.Size([1, 2, 1])

tensor([[[4., 5.],
         [5., 6.]]])


In [36]:
print()
print("==============")
print("Mul vs Matmul")
print("==============")
m1 = torch.FloatTensor([[1,2],[3,4]]) # 2 x 2
m2 = torch.FloatTensor([[1], [2]]) # 2 x 1
print("Shape of Matrix 1: ", m1.size())
print("Shape of Matrix 2: ", m2.size())
print(m1.matmul(m2)) # 2 x 1. 행렬 곱 연산

print()
m1 = torch.FloatTensor([[1,2],[3,4]]) # 2 x 2
m2 = torch.FloatTensor([[1], [2]]) # 2 x 1
print("Shape of Matrix 1: ", m1.size())
print("Shape of Matrix 2: ", m2.size())
print(m1 * m2) # 2 x 2. elementwise
print(m1.mul(m2)) # 2 x 2. elementwise


Mul vs Matmul
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# Mean

In [37]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [38]:
# Can not use mean() on integers
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [39]:
# you can also use t.mean for higher rank tensors to get mean of all elements or mean by particular dimension
t = torch.FloatTensor([[1., 2.],[3., 4.]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [42]:
print('t.mean         : ',t.mean()) # 전체 원소의 평균
print('t.mean(dim=0)  : ',t.mean(dim=0)) # 첫 번째 차원 단위의 평균(세로)
print('t.mean(dim=1)  : ',t.mean(dim=1)) # 두 번째 차원 단위의 평균(가로)
print('t.mean(dim=-1) : ',t.mean(dim=-1))

t,mean         :  tensor(2.5000)
t,mean(dim=0)  :  tensor([2., 3.])
t,mean(dim=1)  :  tensor([1.5000, 3.5000])
t,mean(dim=-1) :  tensor([1.5000, 3.5000])


# Sum

In [43]:
t = torch.FloatTensor([[1., 2.],[3., 4.]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [44]:
print('t.sum()         : ',t.sum()) # 전체 원소의 평균
print('t.sum(dim=0)  : ',t.sum(dim=0)) # 첫 번째 차원 단위의 합(세로)
print('t.sum(dim=1)  : ',t.sum(dim=1)) # 두 번째 차원 단위의 합(가로)
print('t.sum(dim=-1) : ',t.sum(dim=-1))

t.sum()         :  tensor(10.)
t.sum(dim=0)  :  tensor([4., 6.])
t.sum(dim=1)  :  tensor([3., 7.])
t.sum(dim=-1) :  tensor([3., 7.])


# Max and Argmax


In [45]:
t = torch.FloatTensor([[1., 2.],[3., 4.]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


`max` operator returns one value if it is called without an argument

In [47]:
print(t.max())

tensor(4.)


`max` returns 2 values when called with dimension specified.  
the first value is the maximum value, and the second value is the argmax: the index of the element with maximum value

In [50]:
# returns 2 values when called with dimension specified
print(t.max(dim=0))
print()
print('Max:    ', t.max(dim=0)[0]) # 원소
print('Argmax: ', t.max(dim=0)[1]) # 최댓값의 인덱스

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

Max:     tensor([3., 4.])
Argmax:  tensor([1, 1])


In [53]:
print(t.max(dim=1))
print()
print('Max:    ', t.max(dim=1))
print()
print('Argmax: ', t.max(dim=1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

Max:     torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

Argmax:  torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# View
- numpy의 reshape과 유사

In [54]:
t = np.array([[[0,1,2],
              [3,4,5]],
             
             [[6,7,8],
             [9,10,11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [55]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [56]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# Squeeze
- 차원 축소

In [57]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [58]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [62]:
print(ft.squeeze(dim = 0)) 
print(ft.squeeze(dim = 1)) # 두번째 차원 없애기

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3])


# Unsqueeze

In [66]:
ft = torch.Tensor([0,1,2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [64]:
print(ft.unsqueeze(0)) # dim = 0 (3,) => (1,3)
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [67]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [68]:
print(ft.unsqueeze(1)) # dim = 1 (3,) => (3,1)
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [69]:
print(ft.unsqueeze(-1)) # dim = -1 == dim = 1 (3,) => (3,1)
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# Type Casting

In [70]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [72]:
print(ft.float())

tensor([0., 1., 2.])


In [73]:
bt = torch.ByteTensor([True,False,False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [74]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [77]:
bt = (lt == 3)
print(bt)
print(bt.long())

tensor([False, False,  True, False])
tensor([0, 0, 1, 0])


# Concatenate

In [79]:
x = torch.FloatTensor([[1,2],[3,4]]) # (2,2)
y = torch.FloatTensor([[5,6],[7,8]]) # (2,2)

In [80]:
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [81]:
print(torch.cat([x,y],dim=0)) # (4,2)
print(torch.cat([x,y],dim=1)) # (2,4)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stacking

In [82]:
x = torch.FloatTensor([1,4]) # (2,)
y = torch.FloatTensor([2,5]) # (2,)
z = torch.FloatTensor([3,6]) # (2,)

In [83]:
print(torch.stack([x,y,z])) # (3,2)
print(torch.stack([x,y,z], dim=1)) # (2,3)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [85]:
print(x.unsqueeze(0))
print(x.unsqueeze(0).shape)

tensor([[1., 4.]])
torch.Size([1, 2])


In [84]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# Ones and Zeros

In [86]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [88]:
print(torch.ones_like(x)) # x와 같은 크기의 행렬
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-place Operation

In [92]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [94]:
print(x.mul(2.)) # x x 2
print(x) # 깊은 복사. 원본 텐서 수정 x
print(x.mul_(2.))
print(x) # 얕은 복사. 원본 텐서 수정 o

tensor([[ 4.,  8.],
        [12., 16.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[ 4.,  8.],
        [12., 16.]])
tensor([[ 4.,  8.],
        [12., 16.]])


# Miscellaneous

## zip

In [100]:
for x in zip([1,2,3],[4,5,6]):
    print(x)

(1, 4)
(2, 5)
(3, 6)


In [101]:
for x in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x)

(1, 4, 7)
(2, 5, 8)
(3, 6, 9)


In [102]:
for x,y in zip([1,2,3],[4,5,6]):
    print(x,y)
    

1 4
2 5
3 6


In [104]:
for x,y,z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
