In [1]:
import numpy as np

# Numpy

## 1. 넘파이 ndarray 개요

In [2]:
array1 = np.array([1,2,3]) # 1차원 데이터
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) # ndarray의 차원과 크기를 튜플 형태로 나타냄

array2 = np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


## 2. ndarray의 데이터 타입

### 데이터 타입 확인

- ndarray내의 데이터값은 숫자, 문자열, 불 등 모두 가능하다.
- ndarray내의 데이터 타입은 ***같은 데이터 타입***만 가능하다. 즉 한 개의 ndarray 객체에 int와 float가 함께 있을 수 없다.
- ndarray의 데이터 타입은 ***dtype*** 속성으로 확인할 수 있다.

In [4]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))

print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
# 다른 데이터 유형이 섞인 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용

list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype) # 문자열

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # 실수형

['1' '2' 'test'] <U11
[1. 2. 3.] float64


### 데이터 타입 변경

- ***astype()*** 메서드를 이용해서 **데이터 타입 변경**이 가능하다.
- astype()에 인자로 원하는 타입을 문자열로 지정한다.
- 보통 메모리 절약에 사용(float -> int)

In [6]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## 3. ndarray 생성하기 

### arange

- 0부터 (함수 인자 값 -1)까지의 순차적인 값으로 구성된 1차원 ndarray 생성
- default 함수 인자는 stop 값
- 0부터 stop 값 사이

In [7]:
sequence_array = np.arange(10) 
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


### zeros

- 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray 반환

### ones

- 모든 값을 1로 채운 해당 shape을 가진 ndarray 반환

함수 인자로 dtype을 정해주지 않으면 **default**로 **float64** 형의 데이터로 ndarray 채움

In [8]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [9]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## 4. reshape()
    
- ndarray의 차원과 크기를 변경

In [11]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### reshape(-1)

-인자에 -1을 적용하면 원래 ndarray와 호환되는 새로운 shape으로 변환

In [12]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) # (2,5)
print('array2 shape:',array2.shape) 

array3 = array1.reshape(5,-1)# (5,2)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


### reshape(-1,1)

- 원본을 ***2차원***이고, ***여러 개의 로우***를 가졌으며 반드시 ***1개의 칼럼***을 가진 ndarray로 변환

In [14]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist()) # tolist() 메서드로 리스트 자료형으로 변환

# 3차원 -> 2차원
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 -> 2차원
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 5. 인덱싱

### 단일 값 추출

In [16]:
# 1~9까지의 1차원 ndarray 생성
array1 = np.arange(start=1,stop=10)
print('array1:',array1)

# 단일 값 추출
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [18]:
# 인덱스 -1
print('맨 뒤의 값:',array1[-1], '맨 뒤에서 두 번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [20]:
# 단일 인덱스로 ndarray 내의 데이터값 수정
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [21]:
# 다차원 ndarray에서 단일 값 추출
array1d = np.arange(start =1, stop =10)
array2d = array1d.reshape((3,3))
print(array2d)

print('(row=0, col=0) index value :',array2d[0,0])
print('(row=0, col=1) index value :',array2d[0,1])
print('(row=1, col=0) index value :',array2d[1,0])
print('(row=1, col=1) index value :',array2d[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index value : 1
(row=0, col=1) index value : 2
(row=1, col=0) index value : 4
(row=1, col=1) index value : 5


### 슬라이싱

- ***슬라이싱, 팬시 인덱싱, 불린 인덱싱***으로 ***추출된 데이터 세트***는 모두 ***ndarray 타입***
- ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인데스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주 

In [22]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [23]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [24]:
# 2차원 ndarray 슬라이싱

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2]\n',array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n',array2d[1:3, 0:3])
print('array2d[1:3, :]\n',array2d[1:3, :])
print('array2d[:, :]\n',array2d[:, :])
print('array2d[:2, 1:]\n',array2d[:2, 1:])
print('array2d[:2, 0]\n',array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [25]:
print(array2d[0]) # 로우 축(axis 0)의 첫 번째 로우 ndarray를 반환
print(array2d[1])

# 반환되는 ndarray는 1차원
print('array2d[0] shape:',array2d[0].shape, 'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱

- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [26]:
# 2차원 ndarray

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱

- ***조건 필터링***과 ***검색*** 동시에 가능
- step1 : ndarray의 필터링 조건을 [] 안에 기재
- step2 : False 값은 무시하고 True 값에 해당하는 ***인덱스값***만 저장
- step3 : 저장된 인덱스 데이터 세트로 ndarray 조회

In [30]:
array1d = np.arange(start = 1, stop =10)
# [] 안에 array1d > 5 Boolean indexing 사용
array3 = array1d[array1d >5]
print('array1d >5 불린 인덱싱 결과 값:', array3)

array1d >5 불린 인덱싱 결과 값: [6 7 8 9]


In [31]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [32]:
boolean_indexes = np.array([False,False,False,False,False,True, True,True,True])
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


## 6. 행렬의 정렬

### np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 반환

In [35]:
org_array = np.array([3,1,9,5])
print('원본 행렬 : ',org_array)

sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 : ',sort_array1)
print('np.sort() 호출 후 원본 행렬 : ',org_array)

원본 행렬 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]


### ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환, 반환 값은 None

In [37]:
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬 : ',sort_array2)
print('org_array.sort() 호출 후 원본 행렬 : ',org_array)

org_array.sort() 호출 후 반환된 정렬 행렬 :  None
org_array.sort() 호출 후 원본 행렬 :  [1 3 5 9]


In [38]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순 정렬 : ',sort_array1_desc)

내림차순 정렬 :  [9 5 3 1]


In [42]:
# 행렬이 2차원 이상인 경우
array2d = np.array([[8,12],
                   [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('axis = 0(로우 방향 축) 정렬 :\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('axis = 1(칼럼 방향 축) 정렬 :\n', sort_array2d_axis1)

axis = 0(로우 방향 축) 정렬 :
 [[ 7  1]
 [ 8 12]]
axis = 1(칼럼 방향 축) 정렬 :
 [[ 8 12]
 [ 1  7]]


### np.argsort() : 원본 행렬 정렬 시 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때

In [45]:
org_array = np.array([3,1,9,5])

#오름차순
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 오름차순 정렬 시 원본 행렬의 인덱스:', sort_indices)

# 내림차순
sort_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_desc)

<class 'numpy.ndarray'>
행렬 오름차순 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [48]:
name_array = np.array(['john','mike','sarah','kate','samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로  name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로  name_array의 이름 출력: ['john' 'sarah' 'samuel' 'mike' 'kate']


## 7. 선형대수 연산

### 행렬 내적(행렬 곱) : np.dot()

In [53]:
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print('행렬의 내적 결과: \n',dot_product)

행렬의 내적 결과: 
 [[ 58  64]
 [139 154]]


### 전치 행렬

In [54]:
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)

A의 전치 행렬:
 [[1 4]
 [2 5]
 [3 6]]
